In [2]:
import pandas as pd
df = pd.read_csv("../data/raw/25-26.csv")

In [3]:
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [4]:
df.tail()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
354,E0,10/05/2026,14:00,Burnley,Aston Villa,2,2,D,1,1,...,2.03,1.83,NaN,NaN,2.05,1.83,2.00,1.76,2.11,1.89
355,E0,10/05/2026,14:00,Crystal Palace,Everton,2,2,D,1,1,...,2.03,1.83,NaN,NaN,2.03,1.83,1.96,1.79,2.12,1.87
356,E0,10/05/2026,14:00,Nott'm Forest,Newcastle,1,1,D,0,0,...,2.00,1.85,NaN,NaN,2.00,1.85,1.94,1.81,2.09,1.89
357,E0,10/05/2026,16:30,West Ham,Arsenal,0,1,A,0,0,...,1.80,2.05,NaN,NaN,1.90,2.05,1.80,1.95,1.90,2.08
358,E0,11/05/2026,20:00,Tottenham,Leeds,1,1,D,0,0,...,1.83,2.03,NaN,NaN,1.83,2.03,1.78,1.96,1.89,2.11

In [6]:
df.isnull().sum()

Div          0
Date         0
Time         0
HomeTeam     0
AwayTeam     0
            ..
MaxCAHA      0
AvgCAHH      0
AvgCAHA      0
BFECAHH     22
BFECAHA     22
Length: 132, dtype: int64

In [7]:
df.describe()

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
count,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,359.000000,...,359.000000,359.000000,210.000000,210.000000,359.000000,359.000000,359.000000,359.000000,337.000000,337.000000
mean,1.518106,1.228412,0.685237,0.509749,13.766017,11.105850,4.487465,3.857939,10.615599,11.066852,...,1.918830,1.930836,1.964762,1.966143,1.943036,1.958162,1.874067,1.887214,1.990504,1.999318
std,1.178997,1.092471,0.786463,0.750635,4.914448,4.601426,2.228368,2.109936,3.212646,3.341961,...,0.097323,0.096076,0.110116,0.111749,0.092850,0.090325,0.084166,0.085106,0.097657,0.097808
min,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,0.000000,0.000000,3.000000,3.000000,...,1.680000,1.650000,1.680000,1.680000,1.750000,1.750000,1.710000,1.700000,1.810000,1.740000
25%,1.000000,0.000000,0.000000,0.000000,11.000000,8.000000,3.000000,2.000000,8.000000,9.000000,...,1.850000,1.850000,1.880000,1.880000,1.870000,1.880000,1.810000,1.820000,1.910000,1.920000
50%,1.000000,1.000000,1.000000,0.000000,14.000000,11.000000,4.000000,4.000000,10.000000,11.000000,...,1.930000,1.930000,1.970000,1.950000,1.930000,1.960000,1.870000,1.890000,1.980000,2.000000
75%,2.000000,2.000000,1.000000,1.000000,16.500000,14.000000,6.000000,5.000000,13.000000,13.000000,...,2.000000,2.000000,2.040000,2.050000,2.030000,2.030000,1.940000,1.950000,2.060000,2.080000
max,5.000000,5.000000,3.000000,4.000000,35.000000,30.000000,11.000000,11.000000,20.000000,21.000000,...,2.200000,2.150000,2.320000,2.330000,2.350000,2.280000,2.100000,2.080000,2.320000,2.220000

In [9]:
df.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG',
       ...
       'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA',
       'AvgCAHH', 'AvgCAHA', 'BFECAHH', 'BFECAHA'],
      dtype='object', length=132)